version: '3'

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node-1
    environment:
      - discovery.type=single-node
      - node.name=opensearch-node-1
      - discovery.seed_hosts=opensearch-node-1
      - cluster.name=opensearch-cluster
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=weatherTest@123"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - opensearch_data:/usr/share/opensearch/data

  main-app:
    image: main-app-server:latest
    build:
      context: .
      dockerfile: ./weather-main-app/Dockerfile
    container_name: main-app-server
    depends_on:
      - opensearch
    environment:
      - LOG_LEVEL=INFO
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
      - OPENSEARCH_AUTH_USERNAME=admin
      - OPENSEARCH_AUTH_PASSWORD=weatherTest@123
      - WEATHER_API_KEY=cfab3b3ad777d414f6a5ee4d4750d629
      - SCHEDULER_INTERVAL=86400 #Interval in seconds (24h=86400)

  api_server:
    image: weather-api-server:latest
    build:
      context: .
      dockerfile: api-server/Dockerfile
    container_name: api-server
    ports:
      - "8000:8000"
    depends_on:
      - opensearch
    environment:
      - LOG_LEVEL=INFO
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
      - OPENSEARCH_AUTH_USERNAME=admin
      - OPENSEARCH_AUTH_PASSWORD=weatherTest@123

volumes:
  opensearch_data:
    driver: local