version: '3'

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node-1
    environment:
      - discovery.type=single-node
      - node.name=opensearch-node-1
      - discovery.seed_hosts=opensearch-node-1
      - cluster.name=opensearch-cluster
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=weatherTest@123"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
  #  networks:
  #    - internal

  api_server:
    image: weather-api-server:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: api-server
    ports:
      - "8000:8000"
    depends_on:
      - opensearch
    environment:
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200

#networks:
#  internal: {}

  #weather-main-app:
    #  build: 
    #    context: .
    #    dockerfile: ./docker/weather-main-app/Dockerfile
    #    args:
    #      TAG: "0.0.1"
    #  container_name: weather-main
    #  ports:
    #    - "8080:8080"
    #  depends_on:
    #    - opensearch
    #  environment:
    #    - OPENSEARCH_HOST=opensearch
    #    - OPENSEARCH_PORT=9200
    #  networks:
    #    - internal

volumes:
  opensearch_data:
    driver: local