version: '3'

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node-1
    environment:
      - discovery.type=single-node
      - node.name=opensearch-node-1
      - discovery.seed_hosts=opensearch-node-1
      - cluster.initial_master_nodes=opensearch-node-1
      - cluster.name=opensearch-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - opensearch_data:/usr/share/opensearch/data

  #weather_api_server:
  #  build: .
  #  ports:
  #    - "8080:8080"
  #  volumes:
  #    - ./app:/app

  #weather_main_app:
  #  build: .
  #  ports:
  #    - "8080:8080"
  #  volumes:
  #    - ./app:/app


volumes:
  opensearch_data:
    driver: local