PINCODE = "pincode"
LATITUDE = "lat"
LONGITUDE = "lon"
TALUKA = "taluka"
DISTRICT = "district"
STATE = "state"
COUNTRY_CODE = "countryCode"
POST_OFFICE = "postOfficeName"
UPDATE_TIME = "updateTimestamp"

