openapi: "3.0.0"
info:
  title: Weather Watch API
  version: 1.0.0
  description: |-
    The API furnishes data concerning the current and historical AQI 
    conditions for various locations in India.
  termsOfService: http://swagger.io/terms/
  contact:
    email: amolpratap.singh@yahoo.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /v1/currentAirQualityIndex:
    get:
      summary: List the current air quality index of a location
      description: |-
        API used to get the list of Current Air Quality Index Information for India
      operationId: listCurrentAirQualityIndex
      tags:
        - v1_aqi
      parameters:
        - name: pincode
          in: query
          description: |-
            If pincode query attribute provided, response will contain the AQI record 
            for that Geo Location.
          required: false
          schema:
            type: string
        - name: state
          in: query
          description: |-
            If state query attribute provided, response will contain the AQI record 
            for that Geo Location.
          required: false
          schema:
            type: string
        - name: district
          in: query
          description: |-
            If district query attribute provided, response will contain the AQI record 
            for that Geo Location.
          required: false
          schema:
            type: string
        - name: page_ref
          in: query
          description: Pagination Reference Index
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: |-
            It display the list from the startFrom value till th value provided in
            the limit attribute. If limit is not provided it will provide till default 
            value which is 100.
          required: false
          schema:
            type: integer
            format: int32
            default: 100
        - name: order
          in: query
          description: |-
            The response order will be based on the value passed.
            ascending(0) or descending(1)
          required: false
          schema:
            type: integer
            format: int32
            default: 1
        - name: sort_by
          in: query
          description: |-
            The response would be sorted based on one of the attribute passed.
            Attributes are : eventTime, state or district.
          required: false
          schema:
            type: string
      responses:
        "200":
            description: List of Current Weather AQI Information.
            headers:
              x-next:
                description: Link to the next page of response
                schema:
                  type: string
              x-total-count:
                description: Total number of records found for request.
                schema:
                  type: integer
                  format: int32
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/V1AirQualityIndex'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1Error'
components:
  schemas:
    V1Error:
      type: object
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
      required:
        - code
        - message
    V1AirQualityIndex:
      type: object
      properties:
        location:
          type: object
          properties:
            pincode:
              type: integer
            taluka:
              type: string
            district:
              type: string
            state:
              type: string
            countryCode:
              type: string
            postOfficeName:
              type: string
            lon:
              type: number
              format: float
            lat:
              type: number
              format: float
          required:
            - pincode
            - taluka
            - district
            - state
            - countryCode
            - postOfficeName
            - lon
            - lat
        aqi:
          type: integer
        components:
          type: object
          properties:
            Co:
              type: number
              format: float
            NitricOxide:
              type: number
              format: float
            No2:
              type: number
              format: float
            O3:
              type: number
              format: float
            So2:
              type: number
              format: float
            pm2_5:
              type: number
              format: float
            pm10:
              type: number
              format: float
            Nh3:
              type: number
              format: float
          required:
            - Co
            - NitricOxide
            - No2
            - O3
            - So2
            - pm2_5
            - pm10
            - Nh3
        epochTime:
          type: integer
        dt:
          type: integer
        eventTime:
          type: string
          format: date-time
      required:
        - location
        - aqi
        - components
        - epochTime
        - dt
        - eventTime