openapi: "3.0.0"
info:
  title: Weather Watch Geo Location API
  version: 1.0.0
  description: |-
    API provides record related to the Geo Location of India which contains
    pincode, latitude, longtitude, state, districts and taluka. API can be
    extended for further countries to provide the information.
  termsOfService: http://swagger.io/terms/
  contact:
    email: amolpratap.singh@yahoo.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /v1/geo-locations:
    get:
      summary: List all the Geo Location supported by Weather Watch application
      description: |-
        API used to get the list of Geo Location Information supported 
        by Weather Watch application
      operationId: listV1GeoLocation
      tags:
        - v1_geo_locations
      parameters:
        - name: pincode
          in: query
          description: |-
            If pincode query attribute provided, response will contain the record 
            for that Geo Location.
          required: false
          schema:
            type: string
        - name: state
          in: query
          description: |-
            If state query attribute provided, response will contain the record 
            for that Geo Location.
          required: false
          schema:
            type: string
        - name: district
          in: query
          description: |-
            If district query attribute provided, response will contain the record 
            for that Geo Location.
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: |-
            It display the list from the startFrom value till th value provided in
            the limit attribute. If limit is not provided it will provide till default 
            value which is 100.
          required: false
          schema:
            type: integer
            format: int32
            default: 100
      responses:
        "200":
            description: List of Geo Location.
            headers:
              x-next:
                description: Link to the next page of response
                schema:
                  type: string
              x-total-count:
                description: Total number of records found for request.
                schema:
                  type: integer
                  format: int32
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/V1GeoLocation'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1Error'
components:
  schemas:
    V1Error:
      type: object
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
      required:
        - code
        - message
    V1GeoLocation:
      type: object
      properties:
        pincode:
          type: integer
          format: int32
        taluka:
          type: string
        district:
          type: string
        state:
          type: string
        countryCode:
          type: string
        postOfficeName:
          type: string
        lon:
          type: number
          format: float
        lat:
          type: number
          format: float
      required:
        - pincode
        - taluka
        - district
        - state
        - countryCode
        - postOfficeName
        - lon
        - lat
